### PR TITLE
important yet tiny changes to main.js, index.html, and commented out …

### PR DESCRIPTION
**Pull request by rueTH**
to main.js & index.html, and commented out test code on tamela.js
(all discussed and done as a group with everyone else not touching a keyboard :P )

### CODE REVIEW

**Comment by ghost** [comment]
main js script needs to be added

**Comment by rueTH** [comment]
good eye. fixed it.

**Comment by ghost** [comment]
👍  Yaaas!

**Comment by augsismyburger** [comment]
do it

**Comment by preetikrp** [comment]
good

**Pull request merged**
